Implementing rate limit
gocachebr/terraform-provider-gocache pull request #7
Opened 2022-08-25 20:21 UTC by mockthebear

2022-08-25 21:01 UTC, morguesa requested changes

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +Provides a list of type `ratelimit` Smart Rules for a domain, which effectively are just rate limit rules. Smart Rules are the GoCache platform for transforming the request behavior under selected co
behavio**u**r

and the type `ratelimit` **is** like

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `smart_rule` - (Required) Each `smart_rule` block sets a rule. More than one block is allowed. The list have no particular order in contrast to other smartrules, each of those rules defined in the
The list **has** ...

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `request_method` - (Optional) List of HTTP request methods matched by the rule. Possible values `GET`, `POST`, `PUT`, `DELETE`, `HEAD`, `OPTIONS`.
PATCH is not a option?

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `cookie` - (Optional) List of cequest cookie names matched by the rule. This field supports wildcard.
**r**equest cookie

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `cookie_content` - (Optional) Cookie values for a cookie matched by the rule. You need to declare cookie and its value separeted by `=`, like `wp_test=yes`. You can use regex in the value.
separ**a**ted

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `rate_limit_action` - (Required) When `block`, the matched request are denied with status `429`, when `challenge`, a captcha challenge is returned and when `simulate`, the request is allowed, even
the matched request **is** denied

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `rate_limit_amount` - (Required) Amount of requests from a single ip needed to the action to be taken.
a single ip needed **for** the action to be taken.

2022-08-25 21:01 UTC, morguesa commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `rate_limit_period` - (Required) Defines the minimum time windows (seconds) to the requests reach `rate_limit_amount` so the action can be taken. Possible values `86400`, `43200`, `14400`, `3600`,
Defines the minimum time **window** (seconds) for the requests reach `rate_limit_amount` **for** the action can be taken

2022-08-25 21:01 UTC, morguesa commented on gocache/singledomain.go
> +// import (
Remove this file

2022-08-25 21:25 UTC, mockthebear commented on docs/resources/gocache_smart_rules_ratelimit.md
> +* `request_method` - (Optional) List of HTTP request methods matched by the rule. Possible values `GET`, `POST`, `PUT`, `DELETE`, `HEAD`, `OPTIONS`.
no, its not

2022-08-25 21:32 UTC, morguesa approved these changes, later dismissed

2022-08-26 12:06 UTC, Mewbi requested changes

2022-08-26 12:06 UTC, Mewbi commented on docs/resources/gocache_smart_rules_ratelimit.md
> +Some fields can use regex patterns. To know more about regex, see the documentation in https://docs.gocache.com.br/smart_rules/smart_rules-regexp/.
Instead raw hyperlink.

```
...To know more about regex, check the documentation about [Smart Rules Regexp](https://docs.gocache.com.br/smart_rules/smart_rules-regexp/)
```

2022-08-26 12:06 UTC, Mewbi commented on docs/resources/gocache_smart_rules_ratelimit.md
> +Provides a list of type `ratelimit` Smart Rules for a domain, which effectively are just rate limit rules. Smart Rules are the GoCache platform for transforming the request behaviour under selected c
```
... See more in [Rate Limit documentation](https://docs.gocache.com.br/ratelimit/).
```

2022-08-26 18:24 UTC, morguesa approved these changes

2022-08-29 11:50 UTC, Termack approved these changes

2022-08-29 12:17 UTC, Mewbi approved these changes

2022-08-29 13:07 UTC, Mewbi approved these changes

2022-08-29 13:11 UTC, Mewbi approved these changes

2022-08-29 13:12 UTC, Mewbi approved these changes

2022-08-29 13:13 UTC, merged